{% set name = "academic" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ecfc4dadb98f37badfee47968c478df41de6cd94967a4b80e17476ae4a82c76

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - academic = academic.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - toml
    - requests
    - bibtexparser

test:
  imports:
    - academic
    - academic.cli
  commands:
    - academic

about:
  home: https://github.com/sourcethemes/academic-admin
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'An admin tool for Academic'
  description: |
    An admin tool for Academic.

    Features
    - Import publications from BibTeX
    - Import third-party assets to generate an entirely offline site
  dev_url: https://github.com/sourcethemes/academic-admin

extra:
  recipe-maintainers:
    - hoechenberger
