{% set name = "academic" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fdca17514900e78efdeb404f9f5c6155d518aa1158966fcc9a6903e2ceceefe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - academic = academic.cli:main

requirements:
  host:
    - python >=3.11.5
    - pip
  run:
    - python >=3.11.5
    - bibtexparser ~=1.4
    - ruamel.yaml ~=0.17

test:
  imports:
    - academic
    - academic.cli
  commands:
    - academic

about:
  home: https://github.com/wowchemy/bibtex-to-markdown
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Bibtex to Markdown Converter

extra:
  recipe-maintainers:
    - hoechenberger
